version: '3.1'
networks:
    mynetwork:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        networks:
            - mynetwork
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem
            - ./data/vertbot/self-signed.conf:/etc/nginx/snippets/self-signed.conf
            - ./data/vertbot/ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
            - ./https.pki.fredericpinaud.fr.crt:/etc/ssl/certs/nginx-selfsigned.cert
            - ./certificates/https.pki.fredericpinaud.fr.key:/etc/ssl/private/nginx-selfsigned.key
            - ./www:/etc/nginx/html/
        ports:
            - 80:80
            - 443:443
    
    