version: '3.1'
networks:
    mynetwork:

services:
    nginx:
        image: nginx:latest
        container_name: nginx
        networks:
            - mynetwork
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/letsencrypt:/etc/nginx/snippets/letsencrypt
            - ./data/vertbot/conf:/etc/letsencrypt
            - ./data/vertbot/www:/var/www/certbot
            - ./db:/root/pki/db
            - ./config:/root/pki/config
            - ./certificates:/root/pki/certificates
            - ./www:/var/html/www
            - ./www:/etc/nginx/html/
        ports:
            - 80:80
            - 443:443
    
    